### ISSUE TITLE
提几个优化

### ISSUE THREAD

**Issue by djc-Sherlock** [HdShare/GameHelperAction#1]
首先非常感谢，让我解放了双手，其次提几点优化
1.增加个开关控制跑哪个营地
2.日志消息可以通过Push Plus、Server酱等推送到微信，而不是直接写入到文件里
3.王者里，启动游戏-每日福利-每日任务，也可以领取奖励，聊胜于无的蚊子奖励
希望可以考虑下

**Comment by HdShare** [comment]
1.已增加营地开关，通过仓库密钥pg_enable、smoba_enable设置为true启用
2.计划中，预计采用Push Plus
3.等战令系统部分开发完成后，也看看
