### ISSUE TITLE
[BUG] 王者营地-点赞任务可能会重复点击同一篇

### ISSUE THREAD

**Issue by i-CraftY** [HdShare/GameHelperAction#3]
点赞任务虽然输出正常，实际没有完成，应该是最近才出现的问题

**Comment by HdShare** [comment]
> 王者

我-每日福利-任意点赞营地1条内容?
我刚上营地看了, 正常运行, 你重新执行一遍看看

**Comment by HdShare** [comment]
> 今天手动点了，明天再看一下

行

**Comment by HdShare** [comment]
> 执行了好几次还是不行

经过排除, 可能是你账号每天获取的文章列表没啥变化
导致每天点赞是同一篇文章, 所以任务没有完成
你可以查看一下[我 - 浏览历史], 查看今天是否有浏览/点赞内容

**Comment by HdShare** [comment]
> 是的了，我取消点赞后再执行，点的是同一篇😹

后续我看看怎么改, 要么多点几篇, 要么点赞领取完取消点赞内容

**Comment by HdShare** [comment]
> 或许可以获取‘王者荣耀’官方的feedlist，每次点最新的一篇。 我试了，点赞取消后再点赞不算有效记录

第一天点赞后, 先领取奖励, 再取消
第二天再重复
不过获取官方的也行, 就是emmm

**Comment by HdShare** [comment]
已添加领取奖励后清除点赞
可重新拉取项目进行测试
