### ISSUE TITLE
[问题] 关于秘钥的详细获取和填写教程

### ISSUE THREAD

**Issue by windy1021** [HdShare/GameHelperAction#5]
如题，不知道该抓哪条，没找到smoba_sCampUserId等一些值，麻烦大佬教一下

**Comment by windy1021** [comment]
还有就是想问下如果想配置多账号应如何填写，谢谢

**Comment by windy1021** [comment]
马萨卡，，smoba_sCampUserId是不是填自己的营地昵称？

**Comment by HdShare** [comment]
> 如题，不知道该抓哪条，没找到smoba_sCampUserId等一些值，麻烦大佬教一下

smoba_enable设置为true开启王者营地

抓包 我-每日福利
smoba_roleId
smoba_userId
smoba_token
smoba_sMSDKUrlParam

抓包 战绩-更多工具-战令系统
(可填空不开启)
smoba_sOpenId
smoba_sCampUserId

**Comment by HdShare** [comment]
> 还有就是想问下如果想配置多账号应如何填写，谢谢

暂不支持多账号，可自行修改py代码

**Comment by windy1021** [comment]
> > 还有就是想问下如果想配置多账号应如何填写，谢谢
> 
> 暂不支持多账号，可自行修改py代码

谢谢大佬，我去试试，不支持多账号的话那我fork两个是不是就行了

**Comment by windy1021** [comment]
请问下smoba_sMSDKUrlParam要抓哪个链接？我才发现一直好像都填错了，填的是msdkencodeparam，但我找了大半天还是找不到sMSDKUrlParam，所以想问下这个要怎么抓
<img src="https://s3.bmp.ovh/imgs/2024/09/21/003e272d2db48cb4.png"  />

**Comment by windy1021** [comment]
还有就是想请问下感觉pushplus更好用一点，有没有办法用回pushplus推送呢

**Comment by HdShare** [comment]
> 还有就是想请问下感觉pushplus更好用一点，有没有办法用回pushplus推送呢

src/smoba/SmobaEntry.py中
将第5行、182行的ServerChan修改为PushPlus

**Comment by HdShare** [comment]
> 请问下smoba_sMSDKUrlParam要抓哪个链接？我才发现一直好像都填错了，填的是msdkencodeparam，但我找了大半天还是找不到sMSDKUrlParam，所以想问下这个要怎么抓

抓包 战绩-更多工具-战令系统
链接为 https://yxzjfaas.native.qq.com 开头
sMSDKUrlParam 格式大概为source=smoba_zhushou&sig后面省略
