### ISSUE TITLE
[问题] pushplus未推送及登录态失效

### ISSUE THREAD

**Issue by windy1021** [HdShare/GameHelperAction#6]
配置了pushplus的token但是没有收到推送，以及日志中显示登录态失效，但我看任务好像完成了，也不知道到底成功没有🥲辛苦大佬有空的话帮忙看看，感谢
<img src="https://s3.bmp.ovh/imgs/2024/09/14/f7cb8ab8b0791029.png"  />
<img src="https://s3.bmp.ovh/imgs/2024/09/14/474f35b96913f518.png"  />

**Comment by HdShare** [comment]
在最新版本中，已经更换pushplus为serverchan

登录态失效 是战令系统部分的，没啥大影响，后续有空我看看

**Comment by windy1021** [comment]
> 在最新版本中，已经更换pushplus为serverchan
> 
> 登录态失效 是战令系统部分的，没啥大影响，后续有空我看看

啊这样，那请问下这个要如何配置secret

**Comment by HdShare** [comment]
> 啊这样，那请问下这个要如何配置secret

跟之前差不多，通过SERVERCHAN_TOKEN配置

**Comment by windy1021** [comment]
> > 啊这样，那请问下这个要如何配置secret
> 
> 跟之前差不多，通过SERVERCHAN_TOKEN配置

好的谢谢！
