### ISSUE TITLE
[问题] 请问佬关于和平营地秘钥的详细获取

### ISSUE THREAD

**Issue by YangZhaocool** [HdShare/GameHelperAction#7]
会抓 但是不知道在哪抓 佬能帮忙指点一下吗

**Comment by YangZhaocool** [comment]
别的都研究明白在哪抓了 但是这个token没抓明白 抓出来老说失效 0.0

**Comment by HdShare** [comment]
签到请求体里面pg_appid pg_msdkEncodeParam pg_openid pg_sig pg_timestamp pg_roleId 

首页刷新资讯请求体里面pg_userId pg_token

**Comment by YangZhaocool** [comment]
麻烦了 大佬  你不发财谁发财啊 已解决
